raft: install
    maelstrom/maelstrom test -w lin-kv --bin ~/.cargo/bin/maelstrom-raft --node-count 3 --concurrency 4n --rate 30 --time-limit 60 --nemesis partition --nemesis-interval 10 --test-count 10

datomic: install
    maelstrom/maelstrom test -w txn-list-append --bin ~/.cargo/bin/maelstrom-datomic --node-count 2 --time-limit 10 --rate 100

txn: install
    maelstrom/maelstrom test -w txn-rw-register --bin ~/.cargo/bin/maelstrom-txn --node-count 2 --concurrency 2n --time-limit 20 --rate 100 --consistency-models read-committed --availability total --nemesis partition

kafka: install
    maelstrom/maelstrom test -w kafka --bin ~/.cargo/bin/maelstrom-kafka --node-count 2 --concurrency 2n --time-limit 20 --rate 1000

counter: install
    maelstrom/maelstrom test -w g-counter --bin ~/.cargo/bin/maelstrom-counter --node-count 3 --rate 100 --time-limit 20 --nemesis partition

broadcast: install
    maelstrom/maelstrom test -w broadcast --bin ~/.cargo/bin/maelstrom-broadcast --node-count 25 --time-limit 20 --rate 100 --latency 100 --nemesis partition 

generate: install
    maelstrom/maelstrom test -w unique-ids --bin ~/.cargo/bin/maelstrom-unique-id --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition

echo: install
    maelstrom/maelstrom test -w echo --bin ~/.cargo/bin/maelstrom-echo --node-count 1 --time-limit 10

all: echo generate broadcast counter kafka txn datomic

pull:
    curl -L https://github.com/jepsen-io/maelstrom/releases/download/v0.2.3/maelstrom.tar.bz2 | tar -xj

install:
    cargo install --path .

debug:
    maelstrom/maelstrom serve